### ISSUE TITLE
source file versioning

### ISSUE THREAD

**Issue by jaikumar-sharma** [rraptorr/oracle-java8#9]
Hi, I want to sincerely thank you for providing and supporting oracle java build infrastructure for debian. I can build the 'amd64' and 'i386' pefectly on debian 8.0, however, there is no way to upload the source code for 'amd64' and 'i386'  packages on the same reposiotry because source packages are not built as per the new 'version' specified by the user in the changelog.

Would be good if source file names can be renamed as per the latest version being built.

Thank you in advance!
Regards

**Comment by rraptorr** [comment]
Unfortunately I really do not understand what problem you have. All packages are versioned using standard Debian approach. I'm hosting my own repository with packages and I can upload everything just fine.

**Comment by jaikumar-sharma** [comment]
![oracle-java8-version-source-versioning](https://cloud.githubusercontent.com/assets/15682452/11026668/270807c4-86d3-11e5-9a0d-5bce69832ce4.jpg)

Hi, thanks for reply, I've attached the snapshot wherein binary packages have '+ver1' as version suffix i've added in changelog which is being rightly added in binary packages but encircled rounded yellow rectangle shows source files which does not have '+ver1' -- that is what I wanted to highlight in my initial message. 
I've built 'amd64' version of java and and uploaded to my local debian repository suing 'dput *.changes' -- works fine, but as soon as i build 'i386' version of same java then source package names are same as  in 'amd64' and debian repository does not accept the duplicate source package. 

I hope i've clarified it sufficiently. thanks again.

**Comment by rraptorr** [comment]
And why do you try to upload source package twice? Source package, as the name suggests, is architecture independent, it is exactly the same (for both amd64 and i386, since it contains all the files).  Simply upload source package, once, and the upload binary packages (.deb files) for both architectures. This is standard behavior of all Debian packages.

Your +ver1 is not reflected in source package name as it is not supposed to. Source package files contains only upstream files and only upstream version. You have changed Debian revision which has nothing to do with upstream source files. See Debian Policy Manual section 5.6.12 for details.

There is nothing to fix here, you are simply using Debian packages incorrectly.

**Comment by jaikumar-sharma** [comment]
Thanks for quick reply; please see example under http://snapshot.debian.org/package/apt/1.1~exp13/ (for apt debian package) -- which has source and binary versioning (same version suffix in source and binary packages).

I've 64 bit debian jessie virtual machine and i'm using chroot for 32 build in the same. I can not build 32 bit and 64 bit simultaneously ? or I can? is there a possiblity? :-)

**Comment by rraptorr** [comment]
The example (apt) is a native Debian package (no upstream) that have different versioning scheme. Once again this is standard Debian behavior and described in Debian Policy Manual.

I really do not understand your question. You can build both 32 and 64 versions without problems and upload them to the same repository.
